import {
  createClient,
  deleteRequest,
  getRequest,
  headRequest,
  HttpRequestError,
  InvalidJsonResponseError,
  optionsRequest,
  patchRequest,
  postRequest,
  putRequest,
  request,
} from "./requests/rq.js";

import {
  bodyArrayContains,
  bodyArrayContainsItemMatching,
  bodyArrayIsEmpty,
  bodyArrayIsNotEmpty,
  bodyArrayLengthIs,
  bodyContains,
  bodyEquals,
  bodyHasProperty,
  bodyHasLength,
  bodyIncludesProperties,
  bodyIsArray,
  bodyIsEmpty,
  bodyIsNoContent,
  bodyLengthIsAtLeast,
  bodyLengthIsGreaterThan,
  bodyMatches,
  bodyObjectIsEmpty,
  bodyPathEquals,
} from "./assertions/body.js";

import {
  contentTypeIsJson,
  headerExists,
  headerIncludes,
  headerIs,
  headerMatches,
  headerSatisfies,
} from "./assertions/headers.js";

import {
  responseIsAccepted,
  responseIsBadRequest,
  responseIsCreated,
  responseIsClientError,
  responseIsConflict,
  responseIsForbidden,
  responseIsNoContent,
  responseIsNotFound,
  responseIsOk,
  responseIsRedirect,
  responseIsServerError,
  responseIsSuccessful,
  responseIsTooManyRequests,
  responseIsUnprocessableEntity,
  responseIsUnauthorized,
  statusCodeIs,
  statusCodeIs2xx,
  statusCodeIs3xx,
  statusCodeIs4xx,
  statusCodeIs5xx,
  statusCodeIsInRange,
  statusCodeIsOneOf,
} from "./assertions/response.js";

export {
  createClient,
  deleteRequest,
  getRequest,
  headRequest,
  HttpRequestError,
  InvalidJsonResponseError,
  optionsRequest,
  patchRequest,
  postRequest,
  putRequest,
  request,
};

export {
  bodyArrayContains,
  bodyArrayContainsItemMatching,
  bodyArrayIsEmpty,
  bodyArrayIsNotEmpty,
  bodyArrayLengthIs,
  bodyContains,
  bodyEquals,
  bodyHasProperty,
  bodyHasLength,
  bodyIncludesProperties,
  bodyIsArray,
  bodyIsEmpty,
  bodyIsNoContent,
  bodyLengthIsAtLeast,
  bodyLengthIsGreaterThan,
  bodyMatches,
  bodyObjectIsEmpty,
  bodyPathEquals,
};

export {
  contentTypeIsJson,
  headerExists,
  headerIncludes,
  headerIs,
  headerMatches,
  headerSatisfies,
};

export {
  responseIsAccepted,
  responseIsBadRequest,
  responseIsCreated,
  responseIsClientError,
  responseIsConflict,
  responseIsForbidden,
  responseIsNoContent,
  responseIsNotFound,
  responseIsOk,
  responseIsRedirect,
  responseIsServerError,
  responseIsSuccessful,
  responseIsTooManyRequests,
  responseIsUnprocessableEntity,
  responseIsUnauthorized,
  statusCodeIs,
  statusCodeIs2xx,
  statusCodeIs3xx,
  statusCodeIs4xx,
  statusCodeIs5xx,
  statusCodeIsInRange,
  statusCodeIsOneOf,
};

export const lightyRequest = {
  createClient,
  deleteRequest,
  getRequest,
  headRequest,
  HttpRequestError,
  InvalidJsonResponseError,
  optionsRequest,
  patchRequest,
  postRequest,
  putRequest,
  request,
};

export const lightyAssert = {
  bodyArrayContains,
  bodyArrayContainsItemMatching,
  bodyArrayIsEmpty,
  bodyArrayIsNotEmpty,
  bodyArrayLengthIs,
  bodyContains,
  bodyEquals,
  bodyHasProperty,
  bodyHasLength,
  bodyIncludesProperties,
  bodyIsArray,
  bodyIsEmpty,
  bodyIsNoContent,
  bodyLengthIsAtLeast,
  bodyLengthIsGreaterThan,
  bodyMatches,
  bodyObjectIsEmpty,
  bodyPathEquals,
  contentTypeIsJson,
  headerExists,
  headerIncludes,
  headerIs,
  headerMatches,
  headerSatisfies,
  responseIsAccepted,
  responseIsBadRequest,
  responseIsCreated,
  responseIsClientError,
  responseIsConflict,
  responseIsForbidden,
  responseIsNoContent,
  responseIsNotFound,
  responseIsOk,
  responseIsRedirect,
  responseIsServerError,
  responseIsSuccessful,
  responseIsTooManyRequests,
  responseIsUnprocessableEntity,
  responseIsUnauthorized,
  statusCodeIs,
  statusCodeIs2xx,
  statusCodeIs3xx,
  statusCodeIs4xx,
  statusCodeIs5xx,
  statusCodeIsInRange,
  statusCodeIsOneOf,
};

export type {
  Client,
  ClientConfig,
  InvalidJsonResponseErrorOptions,
  MethodConfig,
  RequestConfig,
  RequestResponseType,
  RequestResult,
} from "./requests/rq.js";
export type { HttpRequestErrorOptions } from "./requests/rq.js";
export type {
  RequestEndLogEntry,
  RequestLogger,
  RequestLoggerConfig,
  RequestLoggerLevel,
  RequestStartLogEntry,
  ResponseLogEntry,
} from "./utils/logger.js";
export type { Body, BodyParseError, HttpMethod } from "./types.js";
